services:
  db:
    image: mysql:8.0
    container_name: mcd-db
    restart: always
    environment:
      MYSQL_DATABASE: mcd
      MYSQL_ROOT_PASSWORD: 2200
    volumes:
      - mcd-db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mcd-db-data: