{'items': 
 [{'title': "McDonald's-Titiwangsa DT", 
   'id': 'here:pds:place:458w2864-38a4f1ca0ec0c2c2cfaa5ae558533833', 
   'language': 'ms', 
   'resultType': 'place', 
   'address': {
       'label': "McDonald's-Titiwangsa DT, Jalan Pahang, Titiwangsa, 53200 Bandar Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia", 
       'countryCode': 'MYS', 
       'countryName': 'Malaysia', 
       'stateCode': 'WLY', 
       'state': 'Wilayah Persekutuan Kuala Lumpur', 
       'county': 'Kuala Lumpur', 
       'city': 'Bandar Kuala Lumpur', 
       'district': 'Titiwangsa', 
       'street': 'Jalan Pahang', 
       'postalCode': '53200'
       }, 
    'position': {'lat': 3.17955, 'lng': 101.70038}, 
    'access': [{'lat': 3.17952, 'lng': 101.70048}], 
    'driveThrough': True, 'distance': 4751, 
    'categories': [{'id': '100-1000-0009', 
                    'name': 'Makanan Segera', 
                    'primary': True}], 
    'chains': [{'id': '1566', 'name': "McDonald's"}], 
    'references': [{'supplier': {'id': 'core'}, 'id': '1141471490'}, 
                   {'supplier': {'id': 'core'}, 'id': '1203060761'}, 
                   {'supplier': {'id': 'core'}, 'id': '995114267'}], 
    'foodTypes': [{'id': '800-050', 'name': 'Makanan Segera', 'primary': True}], 
    'contacts': [{'phone': [{'value': '+60340232602'}], 
                'fax': [{'value': '+60340224072'}], 
                'www': [{'value': 'https://www.mcdonalds.com.my/storefinder/index.php'}]}], 
    'openingHours': [{'text': ['Isn-Ahd: 00:00 - 24:00'], 
                      'isOpen': True, 
                      'structured': [{'start': 'T000000', 
                                      'duration': 'PT24H00M', 
                                      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]}], 
    'payment': {'methods': [{'id': 'mastercard', 'accepted': True}]}
    }]
} #type: ignore